packages:
  - "apps/*"
  - "packages/*"

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

catalogs:
  prisma:
    prisma: ^7.2.0
    "@prisma/client": ^7.2.0
  typescript:
    typescript: ^5.9.2
    "@types/node": ^24.10.4
